### ISSUE TITLE
`unsafeIndexCodePoint` and memory safety

### ISSUE THREAD

**Issue by poorlyknitsweater** [channable/alfred-margaret#31]
The module `Data.Text.Utf8` defines the following function:

```haskell
unsafeIndexCodePoint' :: ByteArray -> CodeUnitIndex -> (Int, CodePoint)
unsafeIndexCodePoint' !u8data (CodeUnitIndex !idx)
  | cu0 < 0xc0 = (1, fromIntegral cu0)
  | cu0 < 0xe0 = (2, decode2 cu0 (cuAt 1))
  | cu0 < 0xf0 = (3, decode3 cu0 (cuAt 1) (cuAt 2))
  | otherwise = (4, decode4 cu0 (cuAt 1) (cuAt 2) (cuAt 3))
  where
    cuAt !i = unsafeIndexCodeUnit' u8data $ CodeUnitIndex $ idx + i
    !cu0 = cuAt 0
```

The problem with this function as opposed to `unsafeIndexCodeUnit'`, which simply retrieve a byte at some index, is that it is not enough for the caller to guarantee that the `CodeUnitIndex` is smaller than the number of code units in the passed `Text` to avoid memory safety problems. `unsafeIndexCodePoint'` has the additional precondition that the passed `Text` is a well-formed UTF-8 sequence. Consider the following well-formed UTF-8 sequence:

```
┌──┬──┬──┬───────────┐
│a │b │c │some emoji │
├──┼──┼──┼──┬──┬──┬──┤
│61│62│63│f0│9f│92│a9│
└──┴──┴──┴──┴──┴──┴──┘
```

If a malicious user passes a text value `t` consisting only of the first four bytes to `unsafeIndexCodePoint t 3`, the implementation above will cause a segfault because it is assumed that after the `f0` byte three more bytes follow.

It is therefore important to make sure that any code that uses this function ensures (which includes the UTF-8 Aho-Corasick and Boyer-Moore implementations) that the `Text` values it works with are well-formed. Adding bounds checks to this function would severely degrade its performance :(

**Comment by poorlyknitsweater** [comment]
@fatho

**Comment by poorlyknitsweater** [comment]
Idea: Bounds-checks are only needed for non-ASCII code points (since we assume that `idx` being in bounds is already satisfied by the caller). We could therefore do something like this (`lenghth` isn't in scope but that can be arranged):

```
unsafeIndexCodePoint' :: ByteArray -> CodeUnitIndex -> (Int, CodePoint)
unsafeIndexCodePoint' !u8data (CodeUnitIndex !idx)
  | cu0 < 0xc0 = (1, fromIntegral cu0)
  | idx + 1 >= length = error "..."
  | cu0 < 0xe0 = (2, decode2 cu0 (cuAt 1))
  | idx + 2 >= length = error "..."
  | cu0 < 0xf0 = (3, decode3 cu0 (cuAt 1) (cuAt 2))
  | idx + 3 >= length = error "..."
  | otherwise = (4, decode4 cu0 (cuAt 1) (cuAt 2) (cuAt 3))
  where
    cuAt !i = unsafeIndexCodeUnit' u8data $ CodeUnitIndex $ idx + i
    !cu0 = cuAt 0
```

**Comment by fatho** [comment]
> If a malicious user passes a text value t consisting only of the first four bytes to unsafeIndexCodePoint t 3, the implementation above will cause a segfault because it is assumed that after the f0 byte three more bytes follow.

I don't think this is an attack mode we need to concern ourselves with. Yes, if you construct a text value from the internal constructor and put invalid UTF-8 data in it, then it might crash. But the public text-2.0 interface for creating and manipulating strings should preserve valid UTF-8 contents.

**Comment by poorlyknitsweater** [comment]
Alright :+1:
