### ISSUE TITLE
ContainsAll function ?

### ISSUE THREAD

**Issue by jfaure** [channable/alfred-margaret#4]

**Comment by ruuda** [comment]
You could build this on top of `runText`, similar to how `containsAny` works: https://github.com/channable/alfred-margaret/blob/6ed78a669c67da6ea0584efbe52e2a06867558f7/src/Data/Text/AhoCorasick/Searcher.hs#L109-L115

The accumulator could be something like a vector or hash map of needles encountered, and the step function would mark the needle as seen, and return the updated accumulator as `Aho.Step`. That will get you a vector of which needles are present, and for `containsAll` you can fold `&&` over that.

If you have less than 64 needles, a possible optimization is to use a `Word64` as the accumulator, and [`bit needleIndex`](https://www.stackage.org/haddock/lts-16.15/base-4.13.0.0/Data-Bits.html#v:bit) as the payload. Then the step function would look like

```haskell
f :: Word64 -> Aho.Match -> Aho.Next Word64
f !acc match = acc .|. matchValue match
```
and to test that all needles have been seen, you would check `== (bit numNeedles) - 1` on the result. I suspect that GHC can compile this down to very efficient machine code with a `Word64` accumulator.
