### ISSUE TITLE
Move to text-2.0

### ISSUE THREAD

**Issue by poorlyknitsweater** [channable/alfred-margaret#41]
Progress is on the [chore/text2](https://github.com/channable/alfred-margaret/tree/chore/text2) branch. This branch is basically supposed to preview the changes we'll have to make to move the library to `text-2.0`.

- [x] Init Nix config
- [x] Move to text-2.0 package
- [x] Make CI work with Nix
- [x] Make sure that the benchmarks still work and give the same results
- [x] Upload local Nix derivations to Cachix to allow CI to pass

**Comment by fatho** [comment]
This has been done, thanks @poorlyknitsweater for your effort!

**Comment by unhammer** [comment]
Did this affect benchmark results?

**Comment by fatho** [comment]
@unhammer It did, you can find the comparison of the old and new implementation in our corresponding blogpost in the "Results" section: https://www.channable.com/tech/so-long-surrogatesa

We should probably also update the benchmark in the readme (https://github.com/channable/alfred-margaret/issues/49).

**Comment by unhammer** [comment]
Somehow I missed that blog post, thanks, that's great :-)
