### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by poorlyknitsweater** [channable/alfred-margaret#43]
In order to make depending on `alfred-margaret` easier, we'd like to release it Hackage. We will add two new releases:
- `2.0.0.0` which will depend on UTF-8 `text >= 2`
- `1.1.2.0` which will have some of the improvements of the UTF-8 version while still depending on `text < 2`

The plan is:
- [x] Release current master (2766eb8d3ff6b9ac1df2e1926c784ff6a366496b) as `1.1.2.0`: #44 
- [x] Merge #42 
- [x] Release new master as `2.0.0.0`

In the future, we'll likely only maintain `2.x` versions.

**Comment by poorlyknitsweater** [comment]
@fatho thoughts?

**Comment by fatho** [comment]
Sounds like a reasonable plan!

**Comment by poorlyknitsweater** [comment]
You can release a5a71a7d74028d7d993e9e12662ec493cbe4b064 as `1.1.2.0` now!

**Comment by fatho** [comment]
2.0.0.0 is on Hackage now: https://hackage.haskell.org/package/alfred-margaret-2.0.0.0
