### ISSUE TITLE
Missing python module for haskell benchmark

### ISSUE THREAD

**Issue by HugoPeters1024** [channable/alfred-margaret#50]
I was trying to run the benchmark script using `./benchmark.sh haskell` (from within the nix-shell) but got a missing module in the python script:

```sh
[nix-shell:~/repos/alfred-margaret]$ ./benchmark.sh haskell
Selecting benchmark case...
I will benchmark this executable:

Using data from this directory:
/home/hugo/repos/alfred-margaret/benchmark/data-utf8
And store the results in these files:
haskell-f42e9bd.{stats,results}
Running the benchmark...
Traceback (most recent call last):
  File "/home/hugo/repos/alfred-margaret/./benchmark/benchmark.py", line 3, in <module>
    import clize
ModuleNotFoundError: No module named 'clize'
Done!
```

My experience with nix is currently exclusively using other peoples configs so I'm not quite sure how best to address the issue.

**Comment by HugoPeters1024** [comment]
Strangely this is inside the `default.nix` currently:

```nix
    lib.optionals benchTools [
      (python3.withPackages (pyPkgs: [
        pyPkgs.clize
        pyPkgs.numpy
      ]))
```

However `which python3` points to my system installation and not the nix env

**Comment by fatho** [comment]
Did you follow the instructions in https://github.com/channable/alfred-margaret/tree/master/benchmark#setup? You need an extra argument to `nix run` to get those dependencies (since the benchmark dependencies are quite heavy).

**Comment by HugoPeters1024** [comment]
My bad! Missed those instructions, sorry for the false alarm
